receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317
      http:
        endpoint: collector:4318

processors:
  batch:
  filter/healthcheck:
    traces:
        span:
          - 'attributes["http.target"] == "/healthcheck"'
  redaction/creditcard:
    allow_all_keys: true
    blocked_values:
      - "4[0-9]{12}(?:[0-9]{3})?" ## Visa credit card number
      - "(5[1-5][0-9]{14})"       ## MasterCard number
  attributes/environment:
    actions:
      - key: environment
        value: development
        action: upsert

exporters:
  logging:
  otlp:
    endpoint: "jaeger:4317"
    tls:
        insecure: true
  otlphttp/metrics:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
        insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,filter/healthcheck,redaction/creditcard,attributes/environment]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics]
